'use client';

/**
 * HeroLoopDemo — a precomputed, zero-latency run of the REAL first-analysis
 * experience, opened from example chips under the hero entry field.
 *
 * Why it exists (2026-07-31, launch-day funnel read): of 6 external visitors,
 * 4 left after scrolling the landing and the only one who typed anything pasted
 * an example — nobody arrives with their dilemma loaded. The bridge is showing
 * the actual experience in ~30s, at zero cost and zero wait.
 *
 * Honesty rules (LLM-glue invariant):
 * - Content is generated by the PRODUCTION prompts via scripts/generate-hero-demo.ts
 *   and stored as fixtures — never hand-written analysis, never a live call
 *   pretended. The panel is labeled "미리 준비된 예시" at all times.
 * - Rendering reuses the real workspace cards (AnalysisCard / QuestionCard),
 *   so the demo cannot drift from the product's actual first screen.
 * - The v2 harness asks a SHORT question and offers no options, so the question
 *   card renders exactly that. The example replies underneath are OURS, marked
 *   as examples, and each maps to its own real refined snapshot generated from
 *   that reply — a tap leads to that answer's actual continuation, never a
 *   canned one-size one.
 * - The seal beat shows an example closing line clearly marked as an example;
 *   the return beat states only what the product actually does (comes back on
 *   the check date with the record).
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ArrowRight, PenLine } from 'lucide-react';
import { AnalysisCard } from '@/components/workspace/progressive/shared/AnalysisCard';
import { QuestionCard } from '@/components/workspace/progressive/shared/QuestionCard';
import { EASE } from '@/components/workspace/progressive/shared/constants';
import type { AnalysisSnapshot } from '@/stores/types';
import { HERO_DEMO_EXAMPLES, type HeroDemoExample } from '@/lib/hero-demo-data';
import { track } from '@/lib/analytics';

type Beat = 'problem' | 'analysis' | 'refined' | 'seal' | 'return';
const BEAT_ORDER: Beat[] = ['problem', 'analysis', 'refined', 'seal', 'return'];
const beatGte = (a: Beat, b: Beat) => BEAT_ORDER.indexOf(a) >= BEAT_ORDER.indexOf(b);

function toSnapshot(ex: HeroDemoExample, refinedOption: string | null): { v0: AnalysisSnapshot; v1: AnalysisSnapshot | null } {
  const v0: AnalysisSnapshot = {
    version: 0,
    real_question: ex.initial.real_question,
    insight: ex.initial.insight,
    hidden_assumptions: ex.initial.hidden_assumptions,
    skeleton: ex.initial.skeleton,
    // Integrity scans ran at generation time (fixtures are curated); an empty
    // array = "scanned, nothing found", which lets the card show the insight —
    // matching what a live user sees moments after the stream lands.
    lean_flags: [],
    honesty_flags: [],
  };
  const r = refinedOption ? ex.refined[refinedOption] : null;
  const v1: AnalysisSnapshot | null = r
    ? {
        version: 1,
        real_question: r.real_question,
        insight: r.insight,
        hidden_assumptions: r.hidden_assumptions,
        skeleton: r.skeleton,
        lean_flags: [],
        honesty_flags: [],
      }
    : null;
  return { v0, v1 };
}

export function HeroLoopDemo({
  exampleId,
  locale,
  onClose,
  onStartOwn,
}: {
  exampleId: string;
  locale: 'ko' | 'en';
  onClose: () => void;
  onStartOwn: () => void;
}) {
  const L = (ko: string, en: string) => (locale === 'ko' ? ko : en);
  const examples = HERO_DEMO_EXAMPLES[locale];
  const ex = useMemo(
    () => examples.find((e) => e.id === exampleId) ?? examples[0],
    [examples, exampleId],
  );
  const [beat, setBeat] = useState<Beat>('problem');
  const [answer, setAnswer] = useState<string | null>(null);
  const panelRef = useRef<HTMLDivElement>(null);
  const endRef = useRef<HTMLDivElement>(null);
  const timers = useRef<ReturnType<typeof setTimeout>[]>([]);
  const later = useCallback((fn: () => void, ms: number) => {
    timers.current.push(setTimeout(fn, ms));
  }, []);

  const { v0, v1 } = toSnapshot(ex, answer);

  // Open: lock scroll, focus panel, advance problem → analysis.
  useEffect(() => {
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    panelRef.current?.focus();
    const t = setTimeout(() => setBeat('analysis'), 900);
    const captured = timers.current;
    return () => {
      document.body.style.overflow = prevOverflow;
      clearTimeout(t);
      captured.forEach(clearTimeout);
    };
  }, []);

  // Esc closes.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [onClose]);

  // After each late beat lands, keep it in view.
  useEffect(() => {
    if (beat === 'refined' || beat === 'seal' || beat === 'return') {
      endRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' });
    }
  }, [beat]);

  const handleAnswer = (value: string) => {
    // Value is always one of the authored sample replies — the demo has no free
    // text, because only these replies have a real generated continuation.
    setAnswer(value);
    setBeat('refined');
    track('landing_demo_answer', { example: ex.id, option_index: ex.sampleAnswers.indexOf(value) });
    later(() => setBeat('seal'), 2600);
    later(() => {
      setBeat('return');
      track('landing_demo_complete', { example: ex.id });
    }, 4600);
  };

  return (
    <div
      className="fixed inset-0 z-[100] overflow-y-auto"
      role="dialog"
      aria-modal="true"
      aria-label={L('Argus 예시 체험', 'Argus example walkthrough')}
    >
      {/* Backdrop */}
      <button
        type="button"
        aria-label={L('닫기', 'Close')}
        onClick={onClose}
        className="fixed inset-0 bg-black/45 backdrop-blur-[2px] cursor-default"
      />

      <div className="relative flex min-h-full items-start justify-center px-3 py-6 sm:px-6 sm:py-10">
        <motion.div
          ref={panelRef}
          tabIndex={-1}
          initial={{ opacity: 0, y: 18 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, ease: EASE }}
          className="relative w-full max-w-2xl rounded-2xl bg-[var(--bg)] border border-[var(--border-subtle)] shadow-[var(--shadow-xl)] outline-none"
        >
          {/* Header — honest provenance, always visible */}
          <div className="sticky top-0 z-10 flex items-center justify-between gap-3 rounded-t-2xl border-b border-[var(--border-subtle)] bg-[var(--bg)]/95 px-4 py-3 backdrop-blur sm:px-6">
            <p className="text-[12.5px] font-semibold text-[var(--text-secondary)]">
              {L('미리 준비된 예시 · 실제 첫 화면과 같은 구성', 'A precomputed example · same layout as the real first screen')}
            </p>
            <button
              type="button"
              onClick={onClose}
              aria-label={L('닫기', 'Close')}
              className="shrink-0 rounded-lg p-1.5 text-[var(--text-tertiary)] transition-colors hover:bg-[var(--surface)] hover:text-[var(--text-primary)] cursor-pointer"
            >
              <X size={16} />
            </button>
          </div>

          <div className="space-y-5 px-4 py-5 sm:px-6 sm:py-6">
            {/* The decision, in the user's voice */}
            <motion.div
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.45, ease: EASE }}
              className="flex items-start gap-2.5"
            >
              <span className="mt-[3px] shrink-0 text-[12px] font-bold uppercase tracking-[0.14em] text-[var(--text-tertiary)]">
                {L('나', 'Me')}
              </span>
              <p className="flex-1 text-[14.5px] leading-relaxed text-[var(--text-primary)]">
                {ex.problem}
              </p>
            </motion.div>

            {/* Beat 2 — the real first analysis card */}
            {beatGte(beat, 'analysis') && !v1 && (
              <AnalysisCard snapshot={v0} prevSnapshot={null} isActive locale={locale} />
            )}

            {/* The refined card replaces v0 (same as the live flow: one card, new version) */}
            {v1 && (
              <AnalysisCard snapshot={v1} prevSnapshot={v0} isActive={false} locale={locale} answerCount={1} />
            )}

            {/* Beat 2b — the real question card.
                v2 asks a SHORT question and offers no options, so the card is
                rendered exactly as the product renders it: question only, no
                buttons, no input. The example replies below are ours, and are
                labeled as such — presenting them inside the card would claim
                the product offered choices it did not. */}
            {beat === 'analysis' && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.7, duration: 0.4 }}
                className="space-y-3"
              >
                <QuestionCard
                  question={ex.initial.next_question}
                  onAnswer={handleAnswer}
                  allowFreeText={false}
                  locale={locale}
                  meta={L('1번째 질문', 'Question 1')}
                />
                <div className="rounded-xl border border-dashed border-[var(--border-subtle)] px-4 py-3.5">
                  <p className="mb-2.5 text-[12px] font-semibold text-[var(--text-tertiary)]">
                    {L(
                      '실제로는 여기에 직접 답을 씁니다. 예시 답변을 눌러보세요 —',
                      'You would type your own answer here. Tap an example reply —',
                    )}
                    <br />
                    {L(
                      '각 답변마다 실제로 생성된 후속 분석이 이어집니다.',
                      'each one has its own real, generated continuation.',
                    )}
                  </p>
                  <div className="flex flex-col gap-2">
                    {ex.sampleAnswers.map((reply) => (
                      <button
                        key={reply}
                        type="button"
                        onClick={() => handleAnswer(reply)}
                        className="min-h-11 rounded-lg border border-[var(--border-subtle)] bg-[var(--surface)] px-3.5 py-2.5 text-left text-[13.5px] leading-relaxed text-[var(--text-primary)] transition-colors hover:border-[var(--accent)] cursor-pointer"
                      >
                        {reply}
                      </button>
                    ))}
                  </div>
                </div>
              </motion.div>
            )}

            {/* Echo of the picked answer */}
            {v1 && answer && (
              <div className="flex items-start gap-2.5">
                <span className="mt-[3px] shrink-0 text-[12px] font-bold uppercase tracking-[0.14em] text-[var(--text-tertiary)]">
                  {L('나', 'Me')}
                </span>
                <p className="flex-1 text-[13.5px] leading-relaxed text-[var(--text-secondary)]">{answer}</p>
              </div>
            )}

            {/* Beat 3 — how the loop actually continues (told, not faked) */}
            <AnimatePresence>
              {beatGte(beat, 'seal') && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, ease: EASE }}
                  className="rounded-xl bg-[var(--accent)]/[0.05] px-4 py-4"
                >
                  <p className="mb-1.5 text-[12px] font-bold uppercase tracking-[0.13em] text-[var(--accent)]">
                    {L('마지막 문장은 당신이 씁니다', 'You write the closing line')}
                  </p>
                  <p className="text-[13px] leading-relaxed text-[var(--text-secondary)]">
                    {L(
                      '질문이 몇 번 더 이어질 수 있어요 — 답이 그림을 바꾸지 않으면 거기서 멈춥니다. 정리가 끝나면 AI가 아니라 당신의 한 줄로 마무리해요. 예를 들면:',
                      'A few more questions may follow — and they stop when an answer stops changing the picture. At the end, the record closes with YOUR line, not the AI’s. For example:',
                    )}
                  </p>
                  <p className="mt-2.5 text-[15px] font-semibold leading-relaxed text-[var(--text-primary)]" style={{ fontFamily: 'var(--font-display)' }}>
                    &ldquo;{ex.sealExample}&rdquo;
                  </p>
                  <p className="mt-1.5 text-[12px] text-[var(--text-tertiary)]">
                    {L('예시 문장 · 확인일: 3주 뒤', 'Example line · check date: 3 weeks out')}
                  </p>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Beat 4 — the return */}
            <AnimatePresence>
              {beatGte(beat, 'return') && (
                <motion.div
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, ease: EASE }}
                >
                  <div className="mb-3 flex items-center gap-2.5" aria-hidden>
                    <span className="flex-1 border-t border-dashed border-[var(--border-subtle)]" />
                    <span className="text-[11.5px] font-semibold uppercase tracking-[0.12em] text-[var(--text-tertiary)]">
                      {L('… 3주 뒤 …', '… 3 weeks later …')}
                    </span>
                    <span className="flex-1 border-t border-dashed border-[var(--border-subtle)]" />
                  </div>
                  <div className="rounded-xl border border-[var(--accent)]/25 bg-[var(--surface)] px-4 py-4 shadow-[var(--shadow-sm)]">
                    <p className="mb-1 text-[12px] font-bold uppercase tracking-[0.13em] text-[var(--accent)]">
                      {L('Argus가 기록을 들고 돌아옵니다', 'Argus comes back with the record')}
                    </p>
                    <p className="text-[16px] font-semibold text-[var(--text-primary)]" style={{ fontFamily: 'var(--font-display)' }}>
                      {L('그래서, 어떻게 됐어요?', 'So — how did it go?')}
                    </p>
                    <p className="mt-1.5 text-[13px] leading-relaxed text-[var(--text-secondary)]">
                      {L(
                        '그날의 판단과 전제가 그대로 담긴 기록 앞에서, 현실과 맞춰봅니다. 판단이 쌓이는 건 이 순간부터예요.',
                        'You check what you wrote — judgment and assumptions intact — against what actually happened. This is where judgment starts to compound.',
                      )}
                    </p>
                  </div>

                  {/* CTA row */}
                  <div className="mt-5 flex flex-col gap-2 sm:flex-row">
                    <button
                      type="button"
                      onClick={() => { track('landing_demo_to_input', { example: ex.id }); onStartOwn(); }}
                      className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl px-4 text-[14px] font-semibold text-[var(--accent-fg)] shadow-[var(--shadow-sm)] transition-transform active:scale-[.98] cursor-pointer"
                      style={{ background: 'var(--gradient-gold)' }}
                    >
                      <PenLine size={14} aria-hidden />
                      {L('내 고민으로 시작하기', 'Start with my own decision')}
                      <ArrowRight size={13} aria-hidden />
                    </button>
                    <button
                      type="button"
                      onClick={onClose}
                      className="inline-flex min-h-11 items-center justify-center rounded-xl border border-[var(--border-subtle)] px-4 text-[13px] font-medium text-[var(--text-secondary)] transition-colors hover:text-[var(--text-primary)] cursor-pointer"
                    >
                      {L('닫기', 'Close')}
                    </button>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            <div ref={endRef} />
          </div>
        </motion.div>
      </div>
    </div>
  );
}
