/**
 * generate-hero-demo — regenerate the landing hero demo fixtures.
 *
 * The hero demo (HeroLoopDemo) shows a PRECOMPUTED run of the real first-analysis
 * experience. To keep it honest, its content is generated by the PRODUCTION
 * prompts (buildInitialAnalysisPrompt + buildDeepeningPrompt) against the
 * production default model — never hand-written. When those prompts change
 * meaningfully, re-run this and re-curate src/lib/hero-demo-data.ts:
 *
 *   npx tsx scripts/generate-hero-demo.ts out.json
 *
 * Requires ANTHROPIC_API_KEY in .env.local (never printed). Run from repo root.
 */
import { readFileSync, writeFileSync } from 'fs';
import { buildInitialAnalysisPrompt, buildDeepeningPrompt } from '../src/lib/progressive-prompts';

const MODEL = 'claude-sonnet-5';
const OUT = process.argv[2] || 'hero-demo-out.json';

const env: Record<string, string> = {};
for (const line of readFileSync('.env.local', 'utf8').split('\n')) {
  const m = line.match(/^([A-Z_]+)=(.*)$/);
  if (m) env[m[1]] = m[2].trim();
}
const API_KEY = env.ANTHROPIC_API_KEY;
if (!API_KEY) throw new Error('ANTHROPIC_API_KEY not found in .env.local');

const EXAMPLES: Array<{ id: string; locale: 'ko' | 'en'; problem: string }> = [
  {
    id: 'ko-job',
    locale: 'ko',
    problem: '지금 회사 3년 다녔는데 연봉 25% 올려주는 이직 제안을 받았어. 근데 지금 팀도 좋고 내년에 승진 가능성도 있어서 고민이야.',
  },
  {
    id: 'ko-hire',
    locale: 'ko',
    problem: '1인 디자인 스튜디오를 하는데 일이 밀려서 첫 직원을 뽑을까 고민이야. 월급 줄 만큼 일이 계속 들어올지 확신이 없어.',
  },
  {
    id: 'ko-home',
    locale: 'ko',
    problem: '전세 만기가 다가오는데 집주인이 보증금을 올려달래. 더 올려주고 계속 살지, 대출을 더 받아서 집을 살지 고민이야.',
  },
  {
    id: 'en-job',
    locale: 'en',
    problem: "I got a job offer with a 25% raise, but I like my current team and I'm up for promotion next year. Should I take it?",
  },
  {
    id: 'en-hire',
    locale: 'en',
    problem: "I run a one-person design studio and work keeps piling up. Should I hire my first employee? I'm not sure the work will keep coming in.",
  },
  {
    id: 'en-home',
    locale: 'en',
    problem: 'My lease is ending and the landlord is raising the rent. Do I renew at the higher price, or stretch my budget and buy a place?',
  },
];

interface AnalysisJson {
  request_type?: string;
  real_question?: string;
  insight?: string;
  stakes?: string;
  reversibility?: string;
  hidden_assumptions?: string[];
  skeleton?: string[];
  next_question?: { text: string; subtext?: string; options?: string[] } | null;
}

async function call(system: string, user: string): Promise<{ json: AnalysisJson | null; raw: string }> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': API_KEY,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 4096,
      system,
      messages: [{ role: 'user', content: user }],
    }),
  });
  if (!res.ok) throw new Error(`API ${res.status}: ${(await res.text()).slice(0, 300)}`);
  const data = (await res.json()) as { content?: Array<{ text?: string }> };
  const raw = (data.content || []).map((b) => b.text || '').join('');
  const cleaned = raw.replace(/^```(?:json)?\s*/m, '').replace(/```\s*$/m, '').trim();
  const start = cleaned.indexOf('{');
  const end = cleaned.lastIndexOf('}');
  let json: AnalysisJson | null = null;
  try { json = JSON.parse(cleaned.slice(start, end + 1)) as AnalysisJson; } catch { /* keep raw */ }
  return { json, raw };
}

async function main() {
  const results: unknown[] = [];

  // Stage 1 — initial analyses, all in parallel
  const initials = await Promise.all(EXAMPLES.map(async (ex) => {
    const p = buildInitialAnalysisPrompt(ex.problem, ex.locale);
    const { json, raw } = await call(p.system, p.user);
    console.log(`[initial] ${ex.id}: ${json ? 'ok' : 'PARSE FAIL'} (${raw.length} chars)`);
    return { ex, initial: json, initialRaw: json ? undefined : raw };
  }));

  // Stage 2 — per-option deepening, parallel per example
  for (const { ex, initial, initialRaw } of initials) {
    if (!initial) { results.push({ ...ex, initial: null, initialRaw }); continue; }
    const nq = initial.next_question;
    const options: string[] = (nq && Array.isArray(nq.options) ? nq.options : []).slice(0, 4);
    const snapshotV0 = {
      version: 0,
      real_question: initial.real_question,
      hidden_assumptions: initial.hidden_assumptions || [],
      skeleton: initial.skeleton || [],
      stakes: initial.stakes,
      reversibility: initial.reversibility,
      request_type: initial.request_type,
    } as Parameters<typeof buildDeepeningPrompt>[1];
    type QA = Parameters<typeof buildDeepeningPrompt>[2][number];
    const refined = await Promise.all(options.map(async (opt) => {
      const p = buildDeepeningPrompt(
        ex.problem,
        snapshotV0,
        [{ question: { text: nq!.text }, answer: { value: opt } } as QA],
        1,
        4,
        ex.locale,
      );
      const { json, raw } = await call(p.system, p.user);
      console.log(`[deepen] ${ex.id} :: "${opt.slice(0, 24)}...": ${json ? 'ok' : 'PARSE FAIL'}`);
      return { option: opt, result: json, rawIfFailed: json ? undefined : raw };
    }));
    results.push({ ...ex, initial, refined });
  }

  writeFileSync(OUT, JSON.stringify(results, null, 2), 'utf8');
  console.log(`WROTE ${OUT}`);
}

main().catch((e) => { console.error(e.message); process.exit(1); });
