/**
 * generate-hero-demo — regenerate the landing hero demo fixtures.
 *
 * The hero demo (HeroLoopDemo) shows a PRECOMPUTED run of the real first-analysis
 * experience. To keep it honest, its content is generated by the PRODUCTION
 * prompts (buildInitialAnalysisPrompt + buildDeepeningPrompt) against the
 * production default model — never hand-written. When those prompts change
 * meaningfully, re-run this and re-curate src/lib/hero-demo-data.ts:
 *
 *   npx tsx scripts/generate-hero-demo.ts out.json
 *
 * Requires ANTHROPIC_API_KEY in .env.local (never printed). Run from repo root.
 *
 * WHY THE USER'S REPLIES ARE AUTHORED HERE (2026-08-03, judgment-harness v2):
 * The first version of this script deepened once per `next_question.options`
 * entry. The v2 harness deliberately stopped manufacturing those branches —
 * "Do not manufacture multiple-choice branches. Use a short answer by default.
 * Offer options only when those branches already appear in the user's words."
 * (judgment-harness-v2.ts) — so every regenerated question now comes back as
 * `type: "short"` with no options, and the option loop deepened nothing.
 *
 * So the demo supplies the USER's side of the conversation and nothing else:
 * `sampleAnswers` below are plausible short replies a person would type. Every
 * word the PRODUCT says — the frame line, the analysis, the question, the
 * refined analysis after each reply — is still generated by the production
 * prompts. The panel labels these as example replies; it must never present
 * them as options the product offered.
 */
import { readFileSync, writeFileSync } from 'fs';
import { buildInitialAnalysisPrompt, buildDeepeningPrompt } from '../src/lib/progressive-prompts';

const MODEL = 'claude-sonnet-5';
const OUT = process.argv[2] || 'hero-demo-out.json';

const env: Record<string, string> = {};
for (const line of readFileSync('.env.local', 'utf8').split('\n')) {
  const m = line.match(/^([A-Z_]+)=(.*)$/);
  if (m) env[m[1]] = m[2].trim();
}
const API_KEY = env.ANTHROPIC_API_KEY;
if (!API_KEY) throw new Error('ANTHROPIC_API_KEY not found in .env.local');

const EXAMPLES: Array<{
  id: string;
  locale: 'ko' | 'en';
  problem: string;
  /** Authored SHORT replies — the user's half of the demo, never the product's. */
  sampleAnswers: string[];
}> = [
  {
    id: 'ko-job',
    locale: 'ko',
    problem: '지금 회사 3년 다녔는데 연봉 25% 올려주는 이직 제안을 받았어. 근데 지금 팀도 좋고 내년에 승진 가능성도 있어서 고민이야.',
    sampleAnswers: [
      '팀장님이 연말 평가 때 직접 얘기해주신 거예요',
      '아직 공식적으로 들은 건 아니고 제 예상이에요',
    ],
  },
  {
    id: 'ko-hire',
    locale: 'ko',
    problem: '1인 디자인 스튜디오를 하는데 일이 밀려서 첫 직원을 뽑을까 고민이야. 월급 줄 만큼 일이 계속 들어올지 확신이 없어.',
    sampleAnswers: [
      '지금 계약된 것만 4개월치 정도 밀려 있어요',
      '한 달치쯤 밀렸고 나머지는 들어올 것 같은 정도예요',
    ],
  },
  {
    id: 'ko-home',
    locale: 'ko',
    problem: '전세 만기가 다가오는데 집주인이 보증금을 올려달래. 더 올려주고 계속 살지, 대출을 더 받아서 집을 살지 고민이야.',
    sampleAnswers: [
      '보증금은 5천 더 달라고 하고, 사려면 2억쯤 대출이 더 필요해요',
      '보증금 인상분은 감당되는데 매수는 계산을 아직 안 해봤어요',
    ],
  },
  {
    id: 'en-job',
    locale: 'en',
    problem: "I got a job offer with a 25% raise, but I like my current team and I'm up for promotion next year. Should I take it?",
    sampleAnswers: [
      'My manager brought it up directly in my year-end review',
      "It hasn't been confirmed — it's what I'm expecting",
    ],
  },
  {
    id: 'en-hire',
    locale: 'en',
    problem: "I run a one-person design studio and work keeps piling up. Should I hire my first employee? I'm not sure the work will keep coming in.",
    sampleAnswers: [
      'About four months of signed contracts are backed up right now',
      'Roughly a month is backed up; the rest I only expect',
    ],
  },
  {
    id: 'en-home',
    locale: 'en',
    problem: 'My lease is ending and the landlord is raising the rent. Do I renew at the higher price, or stretch my budget and buy a place?',
    sampleAnswers: [
      "Rent goes up about 15%, and buying would run roughly 30% more per month",
      "I know the new rent, but I haven't priced out what buying would cost",
    ],
  },
];

interface AnalysisJson {
  request_type?: string;
  real_question?: string;
  frame_line?: string;
  framing_confidence?: number;
  insight?: string;
  stakes?: string;
  reversibility?: string;
  hidden_assumptions?: string[];
  premise_candidates?: unknown[];
  skeleton?: string[];
  next_question?: { text: string; subtext?: string; type?: string; options?: string[] } | null;
}

async function call(system: string, user: string): Promise<{ json: AnalysisJson | null; raw: string }> {
  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': API_KEY,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 4096,
      system,
      messages: [{ role: 'user', content: user }],
    }),
  });
  if (!res.ok) throw new Error(`API ${res.status}: ${(await res.text()).slice(0, 300)}`);
  const data = (await res.json()) as { content?: Array<{ text?: string }> };
  const raw = (data.content || []).map((b) => b.text || '').join('');
  const cleaned = raw.replace(/^```(?:json)?\s*/m, '').replace(/```\s*$/m, '').trim();
  const start = cleaned.indexOf('{');
  const end = cleaned.lastIndexOf('}');
  let json: AnalysisJson | null = null;
  try { json = JSON.parse(cleaned.slice(start, end + 1)) as AnalysisJson; } catch { /* keep raw */ }
  return { json, raw };
}

async function main() {
  const results: unknown[] = [];

  // Stage 1 — initial analyses, all in parallel
  const initials = await Promise.all(EXAMPLES.map(async (ex) => {
    const p = buildInitialAnalysisPrompt(ex.problem, ex.locale);
    const { json, raw } = await call(p.system, p.user);
    console.log(`[initial] ${ex.id}: ${json ? 'ok' : 'PARSE FAIL'} (${raw.length} chars)`);
    return { ex, initial: json, initialRaw: json ? undefined : raw };
  }));

  // Stage 2 — deepen once per AUTHORED reply, parallel per example.
  for (const { ex, initial, initialRaw } of initials) {
    if (!initial) { results.push({ ...ex, initial: null, initialRaw }); continue; }
    const nq = initial.next_question;
    if (!nq) { results.push({ ...ex, initial, refined: [] }); continue; }
    const snapshotV0 = {
      version: 0,
      real_question: initial.real_question,
      hidden_assumptions: initial.hidden_assumptions || [],
      skeleton: initial.skeleton || [],
      stakes: initial.stakes,
      reversibility: initial.reversibility,
      request_type: initial.request_type,
    } as Parameters<typeof buildDeepeningPrompt>[1];
    type QA = Parameters<typeof buildDeepeningPrompt>[2][number];
    const refined = await Promise.all(ex.sampleAnswers.map(async (reply) => {
      const p = buildDeepeningPrompt(
        ex.problem,
        snapshotV0,
        [{ question: { text: nq.text }, answer: { value: reply } } as QA],
        1,
        4,
        ex.locale,
      );
      const { json, raw } = await call(p.system, p.user);
      console.log(`[deepen] ${ex.id} :: "${reply.slice(0, 24)}...": ${json ? 'ok' : 'PARSE FAIL'}`);
      return { answer: reply, result: json, rawIfFailed: json ? undefined : raw };
    }));
    results.push({ ...ex, initial, refined });
  }

  writeFileSync(OUT, JSON.stringify(results, null, 2), 'utf8');
  console.log(`WROTE ${OUT}`);
}

main().catch((e) => { console.error(e.message); process.exit(1); });
